services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env
    tty: true
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@dev_db:5432/postgres
      - DB_SHOULD_MIGRATE=true
      - SESSION_TOKEN_SECRET_KEY=dev_secret_key
      - SESSION_TOKEN_DURATION=24h
      - BREVO_API_KEY=${BREVO_API_KEY}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
      - ALLOW_DB_RESET=true
    depends_on:
      dev_db:
        condition: service_healthy
    networks:
      - dev-app-network
    volumes:
      - .:/usr/src/app

  dev_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - dev-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  buckets:
    image: python:3.12-alpine
    command: python -m http.server 8000
    working_dir: /buckets
    ports:
      - "8081:8000"
    networks:
      - dev-app-network
    volumes:
      - ./local_buckets:/buckets

networks:
  dev-app-network:
    driver: bridge

volumes:
  db-data:
