basePath: /
definitions:
  dtos.AddSpriteCategoryRequest:
    properties:
      category_name:
        type: string
    required:
    - category_name
    type: object
  dtos.CharacterInfoResponse:
    properties:
      category_sprites:
        additionalProperties:
          type: string
        type: object
      character_bio:
        type: string
      character_name:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
    type: object
  dtos.CreateAccountRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.CreateAccountResponseDTO:
    properties:
      email:
        type: string
    type: object
  dtos.ErrorResponse:
    properties:
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  dtos.LoginAccountRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.LoginAccountResponseDTO:
    properties:
      access_token:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  dtos.PatchCharacterInfoRequest:
    properties:
      category_sprites:
        additionalProperties:
          type: string
        type: object
      character_bio:
        type: string
      character_name:
        type: string
    type: object
  dtos.SpriteCategoryListResponse:
    properties:
      category_list:
        items:
          $ref: '#/definitions/dtos.SpriteCategoryResponse'
        type: array
    type: object
  dtos.SpriteCategoryResponse:
    properties:
      category_id:
        type: string
      category_name:
        type: string
    type: object
  dtos.SpriteResponse:
    properties:
      sprite_id:
        type: string
      sprite_url:
        type: string
    type: object
  dtos.SpritesListResponse:
    properties:
      sprites_list:
        items:
          $ref: '#/definitions/dtos.SpriteResponse'
        type: array
    type: object
  dtos.VerifyAccountRequestDTO:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  dtos.VerifyAccountResponseDTO:
    properties:
      email:
        type: string
      verified:
        type: boolean
    type: object
  dtos.WorldResponse:
    properties:
      created_at:
        type: string
      data:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  dtos.WorldsListResponse:
    properties:
      amount:
        type: integer
      limit:
        type: integer
      offset:
        type: integer
      worlds:
        items:
          $ref: '#/definitions/dtos.WorldResponse'
        type: array
    type: object
info:
  contact: {}
  description: |-
    This service manages all backend interactions for the feed the realm clients.

    ⚠️ NOTE: All 2xx responses are wrapped in a 'Data envelope'.
    Example: { "data": { "id": "123", "name": "Alice" } }
  title: FeedTheRealm Core Service API
  version: 0.1.0
paths:
  /assets/sprites:
    put:
      consumes:
      - multipart/form-data
      description: Uploads a sprite file.
      parameters:
      - description: Sprite file
        in: formData
        name: sprite
        required: true
        type: file
      - description: Category ID
        in: formData
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Uploaded sprite
          schema:
            $ref: '#/definitions/dtos.SpriteResponse'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: UploadSpriteData
      tags:
      - assets-service
  /assets/sprites/{sprite_id}:
    get:
      description: Downloads the sprite file for a given sprite UUID.
      parameters:
      - description: Sprite UUID
        in: path
        name: sprite_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Sprite file
          schema:
            type: file
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: DownloadSpriteData
      tags:
      - assets-service
  /assets/sprites/categories:
    get:
      description: Retrieves the list of existing categories UUIDs.
      produces:
      - application/json
      responses:
        "200":
          description: Category list
          schema:
            $ref: '#/definitions/dtos.SpriteCategoryListResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetCategoriesList
      tags:
      - assets-service
    post:
      consumes:
      - application/json
      description: Adds a new sprite category.
      parameters:
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/dtos.AddSpriteCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created category
          schema:
            $ref: '#/definitions/dtos.SpriteCategoryResponse'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: AddCategory
      tags:
      - assets-service
  /assets/sprites/categories/{category_id}:
    get:
      description: Retrieves the list of existing sprites UUIDs for a given category
        UUID.
      parameters:
      - description: Category UUID
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sprite list
          schema:
            $ref: '#/definitions/dtos.SpritesListResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetSpritesListByCategory
      tags:
      - assets-service
  /auth/login:
    post:
      consumes:
      - application/json
      description: Log in an existing user
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginAccountRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/dtos.LoginAccountResponseDTO'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Login
      tags:
      - authentication-service
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Signup data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateAccountRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/dtos.CreateAccountResponseDTO'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: UpdateCharacterInfo
      tags:
      - players-service
      summary: Sign up
      tags:
      - authentication-service
  /auth/verify:
    post:
      consumes:
      - application/json
      description: Verify a user account with email verification code
      parameters:
      - description: Verification data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.VerifyAccountRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successful verification (Wrapped in data envelope)
          schema:
            $ref: '#/definitions/dtos.VerifyAccountResponseDTO'
        "400":
          description: Bad request or invalid code
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Verify Account
      tags:
      - authentication-service
  /character/info:
  /players/character:
    get:
      consumes:
      - application/json
      description: Retrieves the name and bio of the session player character
      produces:
      - application/json
      responses:
        "200":
          description: Character info retrieved correctly
          schema:
            $ref: '#/definitions/dtos.CharacterInfoResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetCharacterInfo
      tags:
      - players-service
  /world:
    get:
      consumes:
      - application/json
      description: Retrieves a paginated list of worlds
      parameters:
      - description: Pagination offset (starting index)
        in: query
        name: offset
        required: true
        type: integer
      - description: Pagination limit (max 100)
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Worlds list retrieved correctly
          schema:
            $ref: '#/definitions/dtos.WorldsListResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetWorldsList
      tags:
      - world-service
    post:
      consumes:
      - application/json
      description: Publishes a new world with the provided information
      parameters:
      - description: World Data
    patch:
      consumes:
      - application/json
      description: Updates the name and bio of the session player character
      parameters:
      - description: Character Info data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.WorldRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Published correctly
          schema:
            $ref: '#/definitions/dtos.WorldResponse'
          $ref: '#/definitions/dtos.PatchCharacterInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated correctly
          schema:
            $ref: '#/definitions/dtos.CharacterInfoResponse'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: PublishWorld
      tags:
      - world-service
  /world/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the name and data of the session player world
      parameters:
      - description: World ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: World info retrieved correctly
          schema:
            $ref: '#/definitions/dtos.WorldResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetWorld
      tags:
      - world-service
  /world/reset-database:
    delete:
      consumes:
      - application/json
      description: Clears all data in the database, this is only meant for testing
        and development environments
      produces:
      - application/json
      responses: {}
      summary: ResetDatabase
      tags:
      - world-service
      summary: PatchCharacterInfo
      tags:
      - players-service
swagger: "2.0"
