basePath: /
definitions:
  dtos.AddSpriteCategoryRequest:
    properties:
      category_name:
        type: string
    required:
    - category_name
    type: object
  dtos.CharacterInfoResponse:
    properties:
      character_bio:
        type: string
      character_name:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
    type: object
  dtos.CreateAccountRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.CreateAccountResponseDTO:
    properties:
      email:
        type: string
    type: object
  dtos.ErrorResponse:
    properties:
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  dtos.LoginAccountRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.LoginAccountResponseDTO:
    properties:
      access_token:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
  dtos.SpriteCategoryListResponse:
    properties:
      category_list:
        items:
          $ref: '#/definitions/dtos.SpriteCategoryResponse'
        type: array
    type: object
  dtos.SpriteCategoryResponse:
    properties:
      category_id:
        type: string
      category_name:
        type: string
    type: object
  dtos.SpriteResponse:
    properties:
      sprite_id:
        type: string
      sprite_url:
        type: string
    type: object
  dtos.SpritesListResponse:
    properties:
      sprites_list:
        items:
          $ref: '#/definitions/dtos.SpriteResponse'
        type: array
    type: object
  dtos.UpdateCharacterInfoRequest:
    properties:
      character_bio:
        type: string
      character_name:
        type: string
    type: object
  dtos.VerifyAccountRequestDTO:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  dtos.VerifyAccountResponseDTO:
    properties:
      email:
        type: string
      verified:
        type: boolean
    type: object
info:
  contact: {}
  description: |-
    This service manages all backend interactions for the feed the realm clients.

    ⚠️ NOTE: All 2xx responses are wrapped in a 'Data envelope'.
    Example: { "data": { "id": "123", "name": "Alice" } }
  title: FeedTheRealm Core Service API
  version: 0.1.0
paths:
  /assets/sprites:
    put:
      consumes:
      - multipart/form-data
      description: Uploads a sprite file.
      parameters:
      - description: Sprite file
        in: formData
        name: sprite
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Uploaded sprite
          schema:
            $ref: '#/definitions/dtos.SpriteResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: UploadSpriteData
      tags:
      - assets-service
  /assets/sprites/{sprite_id}:
    get:
      description: Downloads the sprite file for a given sprite UUID.
      parameters:
      - description: Sprite UUID
        in: path
        name: sprite_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Sprite file
          schema:
            type: file
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: DownloadSpriteData
      tags:
      - assets-service
  /assets/sprites/categories:
    get:
      description: Retrieves the list of existing categories UUIDs.
      produces:
      - application/json
      responses:
        "200":
          description: Category list
          schema:
            $ref: '#/definitions/dtos.SpriteCategoryListResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetCategoriesList
      tags:
      - assets-service
    post:
      consumes:
      - application/json
      description: Adds a new sprite category.
      parameters:
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/dtos.AddSpriteCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created category
          schema:
            $ref: '#/definitions/dtos.SpriteCategoryResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: AddCategory
      tags:
      - assets-service
  /assets/sprites/categories/{category_id}:
    get:
      description: Retrieves the list of existing sprites UUIDs for a given category
        UUID.
      parameters:
      - description: Category UUID
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sprite list
          schema:
            $ref: '#/definitions/dtos.SpritesListResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetSpritesListByCategory
      tags:
      - assets-service
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Log in an existing user
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginAccountRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/dtos.LoginAccountResponseDTO'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Login
      tags:
      - authentication-service
  /auth/verify:
    post:
      consumes:
      - application/json
      description: Verify a user account with email verification code
      parameters:
      - description: Verification data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.VerifyAccountRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Successful verification (Wrapped in data envelope)
          schema:
            $ref: '#/definitions/dtos.VerifyAccountResponseDTO'
        "400":
          description: Bad request or invalid code
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Verify Account
      tags:
      - authentication-service
  /players/character:
    get:
      consumes:
      - application/json
      description: Retrieves the name and bio of the session player character
      produces:
      - application/json
      responses:
        "200":
          description: Character info retrieved correctly
          schema:
            $ref: '#/definitions/dtos.CharacterInfoResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: GetCharacterInfo
      tags:
      - players-service
    put:
      consumes:
      - application/json
      description: Updates the name and bio of the session player character
      parameters:
      - description: Character Info data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateCharacterInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated correctly
          schema:
            $ref: '#/definitions/dtos.CreateAccountResponseDTO'
        "400":
          description: Bad request body
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "401":
          description: Invalid credentials or invalid JWT token
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: UpdateCharacterInfo
      tags:
      - players-service
swagger: "2.0"
